module.exports = {
	card_rub: "card_rub",
	card_usd: "card_usd",
	card_uah: "card_uah",
	qiwi_rub: "qiwi_rub",
	qiwi_usd: "qiwi_usd",
	qiwi_eur: "qiwi_eur",
	yamoney_rub: "yamoney_rub",
	payeer_rub: "payeer_rub",
	payeer_usd: "payeer_usd",
	payeer_eur: "payeer_eur",
	perfectmoney_usd: "perfectmoney_usd",
	perfectmoney_eur: "perfectmoney_eur",
	advcash_rub: "advcash_rub",
	advcash_usd: "advcash_usd",
	advcash_eur: "advcash_eur",
	beeline_rub: "beeline_rub",
	mts_rub: "mts_rub",
	megafon_rub: "megafon_rub",
	tele2_rub: "tele2_rub",
	card_privat_uah: "card_privat_uah",
	webmoney_rub: "webmoney_rub",
	webmoney_usd: "webmoney_usd",
	webmoney_eur: "webmoney_eur",
};